name: Build MBI

on:
  [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Update packages
      run: |
        sudo -n apt-get update
        sudo -n apt-get upgrade -y patch autoconf automake diffutils pkgconf fakeroot git file tar bzip2 zstd

    - name: Silence all git safe directory warnings
      run: git config --system --add safe.directory '*'

    - name: Checkout latest libnx commit
      run: |
        git clone --recurse-submodules https://github.com/switchbrew/libnx.git

    - name: Checkout latest libusbhsfs commit
      run: |
        git clone https://github.com/DarkMatterCore/libusbhsfs.git

    - name: Checkout latest Plutonium commit
      run: |
        git clone https://github.com/R-YaTian/Plutonium.git -b catnip
    
    - name: Checkout latest libnx-ipcext commit
      run: |
        git clone https://github.com/R-YaTian/libnx-ext.git -b catnip-ipcext

    - name: Checkout latest libjtjson commit
      run: |
        git clone https://github.com/R-YaTian/libjtjson.git

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"

    - name: Build and install libnx
      run: |
        cd libnx
        make install -j$(nproc)

    - name: Build libusbhsfs dependencies
      run: |
        cd libusbhsfs
        make BUILD_TYPE=GPL install

    - name: Build Plutonium dependencies
      run: |
        cd Plutonium/Plutonium
        catnip -T switch -S . -B build install

    - name: Build libnx-ipcext dependencies
      run: |
        cd libnx-ext
        catnip -T switch -S . -B build install

    - name: Build libjtjson dependencies
      run: |
        cd libjtjson
        catnip -T switch -S . -B build install

    - name: Build MBI
      run: |
        make -j$(nproc)

    - uses: actions/upload-artifact@master
      with:
        name: MBI
        path: MBI.nro
        if-no-files-found: error
